REMARK   1 PQR file generated by the pqr.tpl template that
REMARK   1 is used by PolyLibScan.helpers.to_pqr.
{% for coords in pymol -%}
{{'ATOM   {:>4} {:>4} {:<3} {} {:>3}{}    {:>7.3f} {:>7.3f} {:>7.3f} {:>7.4f} {:>6.4f}'.format(coords['id'], coords['ele'], coords['res_name'], coords['chain'], coords['res_id'], coords['iCode'], coords['x'], coords['y'], coords['z'], coords['charge'], coords['radius']) }}
{% endfor -%}
TER
